"""Generate manuscript numbers/tables exclusively from the active clean results."""
from pathlib import Path
import json,hashlib
import pandas as pd
ROOT=Path(__file__).resolve().parents[1];RUN=ROOT/'03_result/reevaluation_context_20260925';OUT=RUN/'manuscript_assets';SRC=RUN/'figures/source_data'
OUT.mkdir(exist_ok=True)
def esc(s):
 return str(s).replace('&',r'\&').replace('_',r'\_').replace('%',r'\%')
def table(file,caption,label,columns,rows,headers,wide=True):
 env='table*' if wide else 'table'
 text='\n'.join([r'\begin{'+env+r'}[p]',r'\centering\fontfamily{ptm}\selectfont\small',r'\caption{'+caption+'}',r'\label{'+label+'}',r'\setlength{\tabcolsep}{4pt}',r'\begin{tabularx}{\linewidth}{'+columns+'}',r'\toprule',' & '.join(headers)+r' \\',r'\midrule',*[' & '.join(row)+r' \\' for row in rows],r'\bottomrule',r'\end{tabularx}',r'\end{'+env+'}',''])
 (OUT/file).write_text('% Generated by build_selected_context_assets.py; validation-context-20260925.\n'+text)
a=pd.read_csv(SRC/'main_summary.csv');pairs=pd.read_csv(SRC/'paired_greenhouse_tests.csv');extended=pd.read_csv(SRC/'all_model_summary.csv');bit=a.set_index('model').loc['BiTFI-TimesFM3'];cov=a.set_index('model').loc['TimesFM3.0-COV-SPA'];test=pairs.set_index('reference').loc['TimesFM3.0-COV-SPA'];mt=json.loads((SRC/'moment_tuning_statistics.json').read_text());bb=pd.read_csv(SRC/'bitfi_backbone_comparison.csv').iloc[0]
nums={ 'BiTFINMAE':f'{bit.NMAE:.4f}','BiTFISD':f'{bit.SD:.4f}','BiTFICILow':f'{bit.CI_low:.4f}','BiTFICIHigh':f'{bit.CI_high:.4f}','CovNMAE':f'{cov.NMAE:.4f}','CovReduction':f'{test.reduction_percent:.2f}','CovReductionLow':f'{test.CI_low:.2f}','CovReductionHigh':f'{test.CI_high:.2f}','MainHolmP':f'{test.holm_p:.4f}','MomentZero':f"{mt['zero_shot_NMAE']:.4f}",'MomentTuned':f"{mt['head_tuned_NMAE']:.4f}",'MomentGain':f"{mt['relative_reduction_percent']:.2f}",'MomentLow':f"{mt['CI_low']:.2f}",'MomentHigh':f"{mt['CI_high']:.2f}",'ChronosBiTFI':f'{bb.Chronos2_NMAE:.4f}','BackboneGain':f'{bb.TFM3_reduction_percent:.2f}','BackboneP':f'{bb.paired_wilcoxon_p:.4f}'}
for m,prefix in [('TimesFM3.0','Uni'),('TimesFM3.0-COV','Local'),('SAITS','Saits'),('AG-LightGBM','Light'),('LI','Linear')]:nums[prefix+'NMAE']=f"{a.set_index('model').loc[m,'NMAE']:.4f}"
nums['ForwardNMAE']=f"{extended.set_index('model').loc['BiTFI-TimesFM3-fwd','NMAE']:.4f}"
gap=pd.read_csv(SRC/'gap_scenario_greenhouse_scores.csv').groupby(['model','scenario','gap_length_h']).NMAE.mean()
for sc in 'ABC':
 for h,n in [(6,'Short'),(24,'Day'),(168,'Long')]:nums['Gap'+sc+n]=f"{gap.loc[('BiTFI-TimesFM3',sc,h)]:.4f}"
var=pd.read_csv(SRC/'variable_greenhouse_scores.csv').groupby(['model','variable']).NMAE.mean().unstack();season=pd.read_csv(SRC/'season_greenhouse_scores.csv').groupby(['model','group_value']).NMAE.mean().unstack()
for v,n in [('Tin','Indoor'),('Tout','Outdoor'),('RH','Humidity'),('CO2','Carbon'),('Rad','Radiation')]:nums[n+'NMAE']=f"{var.loc['BiTFI-TimesFM3',v]:.4f}"
for se in ['spring','summer','fall','winter']:nums[se.capitalize()+'NMAE']=f"{season.loc['BiTFI-TimesFM3',se]:.4f}"
(OUT/'numbers.tex').write_text('% Generated numerical claims; source CSVs hashed in manuscript_assets.json.\n'+''.join('\\newcommand{\\'+k+'}{'+v+'}\n' for k,v in nums.items()))
rows=[[esc(r.label),f'{r.NMAE:.4f}',f'{r.SD:.4f}',f'[{r.CI_low:.4f}, {r.CI_high:.4f}]'] for r in a.sort_values('NMAE').itertuples()]
table('overall.tex','Overall reconstruction error across 10 test greenhouses. NMAE is weighted by evaluated hours within each greenhouse, then averaged equally across greenhouses. SD is the between-greenhouse standard deviation; intervals are percentile greenhouse bootstrap 95\\% confidence intervals. MOMENT denotes the validation-selected fine-tuned head.','tab:overall','Xrrr',rows,['Configuration','NMAE','SD',r'95\% CI'])
models=['LI','SeasonalNaive','AG-LightGBM','Spatial-Ridge','SAITS','MOMENT-FT','TimesFM3.0-COV-SPA','BiTFI-TimesFM3'];labels={'LI':'Linear interpolation','SeasonalNaive':'Seasonal naive','AG-LightGBM':'LightGBM','Spatial-Ridge':'Spatial ridge','SAITS':'SAITS','MOMENT-FT':'MOMENT','TimesFM3.0-COV-SPA':'TimesFM3','BiTFI-TimesFM3':'BiTFI'}
rows=[]
for m in models:
 row=[labels[m]]
 for v in ['Tin','Tout','RH','CO2','Rad']:
  value=f'{var.loc[m,v]:.4f}';row.append(r'\textbf{'+value+'}' if var.loc[m,v]==var.loc[models,v].min() else value)
 rows.append(row)
table('variables.tex','Variable-specific mean greenhouse NMAE for the 8 configurations in Figures~4--5. TimesFM3 includes local and cross-greenhouse covariates; BiTFI uses TimesFM3. Bold entries are lowest within the displayed comparison.','tab:variable','Xrrrrr',rows,['Model',r'$T_{\mathrm{in}}$',r'$T_{\mathrm{out}}$','RH',r'CO$_2$','Rad'])
rows=[[esc(a.set_index('model').loc[r.reference,'label']),f'{r.reduction_percent:.2f}',f'[{r.CI_low:.2f}, {r.CI_high:.2f}]',f'{r.wilcoxon_p:.4f}',f'{r.holm_p:.4f}'] for r in pairs.itertuples()]
table('paired_tests.tex','Paired comparisons with BiTFI (TimesFM3), using 10 greenhouse scores. Reduction is 100 times one minus the ratio of mean NMAEs. Positive values favor BiTFI. Intervals use paired greenhouse bootstrap resampling; two-sided Wilcoxon tests are Holm-adjusted across these 8 comparisons.','tab:paired','Xrrrr',rows,['Reference',r'Reduction (\%)',r'95\% CI (\%)',r'$p$',r'Holm $p$'],wide=False)
rows=[]
full=[]
for p in sorted((RUN/'evaluation').glob('*/complete.json')):
 if 'pilot' in p.parent.name or p.parent.name.startswith('CAFI'):continue
 d=pd.read_csv(p.parent/'results.csv');d=d[d.group_type=='all'];q=d.assign(w=d.NMAE*d.n_eval).groupby('greenhouse')[['w','n_eval']].sum();z=q.w/q.n_eval;name=p.parent.name;lab=extended.set_index('model').label.get(name,{'MOMENT':'MOMENT (zero-shot)','CAFI':'CAFI (Chronos 2, R5)','CAFI-R1':'CAFI (Chronos 2, R1)','CAFI-TimesFM3':'CAFI (TimesFM3, R5)','CAFI-TimesFM3-R1':'CAFI (TimesFM3, R1)'}.get(name,name));full.append((lab,float(z.mean()),float(z.std()),name))
assert len(full)==19
for lab,mu,sd,name in sorted(full,key=lambda x:x[1]):rows.append([esc(lab),f'{mu:.4f}',f'{sd:.4f}'])
table('all_configurations.tex','All 19 evaluated settings, ordered by mean NMAE. Zero-shot MOMENT is retained only as a training-effect control. Figure~S1 displays the other 18 configurations.','tab:all','Xrr',rows,['Configuration','NMAE','SD'],wide=False)
rows=[]
for m in ['LI','SeasonalNaive','AG-LightGBM','SAITS','MOMENT-FT','TimesFM3.0','TimesFM3.0-COV-SPA','BiTFI-TimesFM3']:
 lab=a.set_index('model').loc[m,'label'];rows.append([esc(lab),*[f'{season.loc[m,v]:.4f}' for v in ['spring','summer','fall','winter']]])
table('seasons.tex','Seasonal mean greenhouse NMAE corresponding to Figure~S4. Available greenhouse scores are equally weighted within each season.','tab:season','Xrrrr',rows,['Configuration','Spring','Summer','Fall','Winter'],wide=False)
meta=pd.read_excel(ROOT/'01_data/meta_data.xlsx');meta['name']=meta.name.str.strip();meta=meta.set_index('name');coverage=pd.read_csv(SRC/'Figure1_profile/coverage.csv');rows=[];counts={}
for role in ['train','test']:
 d=coverage[coverage.role==role];counts[role]={}
 for i,r in enumerate(d.itertuples(),1):
  info=meta.loc[r.name];plant=str(info['plant']).strip().replace('_',' ').title();counts[role][plant]=counts[role].get(plant,0)+1
  dates=f"{pd.Timestamp(r.start):%b %Y}--{pd.Timestamp(r.end):%b %Y}"
  rows.append([f'{role.title()} {i:02}',esc(plant),f"{float(info['area (m2)']):,.0f}",dates])
assert len(rows)==34
table('greenhouses.tex','Study greenhouses in the exact row order of Figure~1. Train/Test numbers match Figure~1; the raw site-code mapping is retained in the accompanying source data. Areas and crops come from the site metadata; periods use the actual series coverage in the figure source data.','tab:greenhouse_list','lXrl',rows,['Split / no.','Crop',r'Area (m$^2$)','Period'])
coverage.assign(display_id=coverage.role.str.title()+' '+(coverage.groupby('role').cumcount()+1).astype(str).str.zfill(2)).merge(meta.loc[coverage.name].reset_index(),on='name',validate='one_to_one').to_csv(OUT/'greenhouse_metadata_checked.csv',index=False)
manifest={'protocol':'validation-context-20260925','model_settings':19,'crop_counts':counts,'sources':{str(p.relative_to(ROOT)):hashlib.sha256(p.read_bytes()).hexdigest() for p in [*SRC.glob('*.csv'),*SRC.glob('*.json'),ROOT/'01_data/meta_data.xlsx',SRC/'Figure1_profile/coverage.csv']},'generated_numbers':nums,'raw_model_IDs':[x[3] for x in full]}
(OUT/'manuscript_assets.json').write_text(json.dumps(manifest,indent=2));print('Generated tables and numerical macros.',counts)
