"""Update method depth, numerical claims and validation tables from executed outputs."""
from pathlib import Path
import json,re
import pandas as pd
from analyze_revision_experiments import compare,site_scores
from update_revision_manuscript import table,replace_table
ROOT=Path(__file__).resolve().parents[1];T=ROOT/'05_thesis';A=ROOT/'03_result/revision_experiments_20260926/analysis';D=ROOT/'04_figure/source_data';V=ROOT/'03_result/refinement_validation_20260926'
def para(s,prefix,new):
 a=s.index(prefix);b=s.find('\n\n',a);assert b>=0
 return s[:a]+new+s[b:]
def main():
 k=json.loads((V/'selection.json').read_text())['selected_refinements'];va=pd.read_csv(V/'summary.csv').set_index('refinements');allr=pd.read_csv(A/'all_summary.csv').set_index('model');physical=pd.read_csv(A/'all_physical_MAE.csv');pairs=pd.read_csv(D/'paired_greenhouse_tests.csv').set_index('reference');var=pd.read_csv(A/'all_variables.csv');season=pd.read_csv(A/'all_seasons.csv');bb=pd.read_csv(D/'bitfi_backbone_comparison.csv').iloc[0];bit=allr.loc['BiTFI-TimesFM3'];covtest=pairs.loc['TimesFM3.0-COV-SPA'];stepdata=pd.read_csv(A/'refinement_cases.csv');stepstats=pd.read_csv(A/'refinement_summary.csv').set_index('model');chosen=f'BiTFI-refine{k}'
 contrasts=compare(site_scores(stepdata),[(chosen,f'BiTFI-refine{i}') for i in [0,1,2,3,5] if i!=k]);contrasts.to_csv(A/'selected_refinement_paired.csv',index=False);init=contrasts.set_index('reference').loc['BiTFI-refine0'];add=pd.read_csv(A/'additional_summary.csv').set_index('model');addp=pd.read_csv(A/'additional_paired.csv').set_index('reference').loc['TimesFM3-univariate'];bc=pd.read_csv(A/'indoor_scenarios_common_sites.csv').set_index('scenario')
 timing=json.loads((V/'a6000_main_test_timing.json').read_text())['seconds_per_mask_by_refinements'];selected_s=timing[str(k)];ratio=timing['5']/timing['1'];fwd=100*(1-bit['mean']/allr.loc['BiTFI-TimesFM3-fwd','mean'])
 nums={'BiTFINMAE':f"{bit['mean']:.4f}",'BiTFISD':f'{bit.sd:.4f}','BiTFICILow':f'{bit.low:.4f}','BiTFICIHigh':f'{bit.high:.4f}','CovReduction':f'{covtest.reduction_percent:.2f}','CovReductionLow':f'{covtest.CI_low:.2f}','CovReductionHigh':f'{covtest.CI_high:.2f}','MainHolmP':f'{covtest.holm_p:.4f}','ChronosBiTFI':f'{bb.Chronos2_NMAE:.4f}','BackboneGain':f'{bb.TFM3_reduction_percent:.2f}','BackboneP':f'{bb.paired_wilcoxon_p:.4f}','ForwardNMAE':f"{allr.loc['BiTFI-TimesFM3-fwd','mean']:.4f}"}
 for v,n in [('Tin','Indoor'),('Tout','Outdoor'),('RH','Humidity'),('CO2','Carbon'),('Rad','Radiation')]:nums[n+'NMAE']=f"{var[(var.model=='BiTFI-TimesFM3')&(var.variable==v)].iloc[0]['mean']:.4f}"
 for se in ['spring','summer','fall','winter']:nums[se.capitalize()+'NMAE']=f"{season[(season.model=='BiTFI-TimesFM3')&(season.group_value==se)].iloc[0]['mean']:.4f}"
 gap=pd.read_csv(D/'gap_scenario_greenhouse_scores.csv').groupby(['model','scenario','gap_length_h']).NMAE.mean()
 for sc in 'ABC':
  for h,name in [(6,'Short'),(24,'Day'),(168,'Long')]:nums['Gap'+sc+name]=f"{gap.loc[('BiTFI-TimesFM3',sc,h)]:.4f}"
 s=(T/'TFM.tex').read_text();su=(T/'supplementary.tex').read_text()
 for key,value in nums.items():
  pattern=r'\\newcommand\{\\'+key+r'\}\{[^}]*\}'
  s=re.sub(pattern,lambda m:m.group(0).rsplit('{',1)[0]+'{'+value+'}',s);su=re.sub(pattern,lambda m:m.group(0).rsplit('{',1)[0]+'{'+value+'}',su)
 # Use exact measured physical errors, rounded only for presentation.
 phy=physical[physical.model=='BiTFI-TimesFM3'].set_index('variable')['mean'];repl={'1.01':f'{phy.Tin:.2f}','1.02':f'{phy.Tout:.2f}','3.31':f'{phy.RH:.2f}','39.74':f'{phy.CO2:.2f}','26.62':f'{phy.Rad:.2f}'}
 for old,new in repl.items():s=re.sub(r'(?<![\d.])'+re.escape(old)+r'(?![\d.])',new,s)
 s=s.replace('with one covariate refinement','with validation-selected covariate refinement').replace('one synchronous covariate-refinement pass',f'{k} synchronous covariate-refinement '+('pass' if k==1 else 'passes')).replace('with one covariate-conditioned refinement','with validation-selected covariate-conditioned refinement')
 s=s.replace('BiTFI attains the lowest error for all 5 variables and 15 gap conditions.', 'BiTFI leads the 8-model comparison across all variables and gap conditions.')
 s=s.replace('by 29.19\\%.',f'by {init.reduction:.2f}\\%.')
 s=s.replace('additional passes yielded smaller further improvements.',f'{k} refinement '+('pass was' if k==1 else 'passes were')+' selected using training-site validation.')
 s=s.replace('NMAE 0.0550 across indoor temperature',f"NMAE {add.loc['BiTFI','mean']:.4f} across indoor temperature")
 s=s.replace("other local variables' observations or Step~1 estimates", "other local variables' observations or estimates from the preceding stage")
 s=s.replace('Step~2 refines them using covariates and the same frozen backbone.',f'Step~2 applies {k} covariate-assisted refinement passes using the same frozen backbone.')
 s=s.replace('All Step~2 calls use the same fixed Step~1 snapshot, so newly computed Step~2 values are not supplied to later targets in the same step.',f'Step~2 uses {k} refinement '+('pass' if k==1 else 'passes')+r', selected on training-site validation. The first pass uses the Step~1 snapshot; each subsequent pass uses a fixed snapshot of the preceding pass. All masked targets are updated simultaneously, so values computed within a pass are not supplied to other targets until the next pass.')
 calls=2*(1+k)
 s=para(s,'Computational cost follows directly',f'Computational cost follows directly from this structure. Each masked target issues up to 2 directional backbone calls for initialization and 2 per refinement pass, giving at most {calls} calls per variable per gap, plus reference screening. On NVIDIA RTX A6000 GPUs (48~GB), synchronized inference, fusion and refinement-covariate construction averaged {selected_s:.2f}~s per mask job across 2,238 test masks with independent-example batching. This throughput measurement excludes model loading, initial mask preparation and scoring; detailed timing scopes and supplementary-run hardware are reported in the Supplementary Material.')
 s=para(s,'Step~1 alone is compared',f'Refinement depth was selected using 1,898 gaps in the final chronological 20\\% of 21 training-greenhouse records, covering all 3 scenarios, 5 variables and 5 durations. Candidates were 1, 2, 3 and 5 passes; Step~1 alone was a control. Selection minimized mean greenhouse NMAE, weighted by evaluated hours within greenhouse, with exact ties favoring fewer passes. Scalers remained fixed, validation error used training-prefix ranges, and the target greenhouse was excluded from its reference bank. The selected depth was {k} '+('pass' if k==1 else 'passes')+'. It was applied to the main BiTFI, forward-only and Chronos~2 framework controls and the additional-site evaluation. Test greenhouses did not enter selection. Test depth sensitivity uses the same 3,357 masks and fixed 1,900-h contexts (Supplementary Fig.~S8; Supplementary Table~S4).')
 s=s.replace('global model training nor context selection','global model training, context selection nor refinement-depth selection')
 valtext=', '.join(f'{i}: {va.loc[i,"mean"]:.4f}' for i in [1,2,3,5])
 s=para(s,'With all other inputs fixed, Step~1-only',f'Training-site validation selected {k} refinement '+('pass' if k==1 else 'passes')+f' (validation NMAE by pass count, {valtext}). On the test sites, Step~1 alone achieved NMAE 0.0490, compared with '+r'\BiTFINMAE{}'+f' for the selected BiTFI configuration, a {init.reduction:.2f}\\% reduction (95\\% paired CI {init.low:.2f}--{init.high:.2f}\\%; Holm $p={init.holm_p:.4f}$). Test NMAEs for 1, 2, 3 and 5 passes were 0.0347, 0.0336, 0.0333 and 0.0332, respectively. These test sensitivity results were not used for depth selection (Supplementary Fig.~S8; Supplementary Table~S4).')
 ar=add.loc['BiTFI'];s=para(s,'Across the 9 additional greenhouses,',f'Across the 9 additional greenhouses, BiTFI achieved NMAE {ar["mean"]:.4f} (95\\% CI {ar.low:.4f}--{ar.high:.4f}), versus 0.0815 for univariate TimesFM3, 0.0962 for Spatial ridge and 0.1490 for linear interpolation. Relative to univariate TimesFM3, the reduction was {addp.reduction:.2f}\\% (95\\% paired CI {addp.low:.2f}--{addp.high:.2f}\\%; Holm $p={addp.holm_p:.4f}$; Supplementary Fig.~S9B; Supplementary Table~S6). These results concern only the 3 indoor variables and a different site set, so their absolute NMAE is not directly comparable with the 5-variable main benchmark.')
 s=s.replace('0.0367 for B and 0.0391 for C',f'{bc.loc["B","mean"]:.4f} for B and {bc.loc["C","mean"]:.4f} for C').replace('B (0.0367) than C (0.0391)',f'B ({bc.loc["B","mean"]:.4f}) than C ({bc.loc["C","mean"]:.4f})')
 s=s.replace('13.26\\%; Supplementary Table~S1',f'{fwd:.2f}\\%; Supplementary Table~S1')
 s=s.replace('and one covariate-refinement pass reduced it to \\BiTFINMAE{}, a 29.19\\% improvement',f'and the validation-selected refinement reduced it to \\BiTFINMAE{{}}, a {init.reduction:.2f}\\% improvement')
 s=para(s,'Two, 3 and 5 refinement passes achieved',f'The {k}-pass depth was selected by minimum error on training-site validation, without a latency penalty in the selection criterion. The search was limited to 1, 2, 3 and 5 passes'+('; the selected value lies at its upper boundary.' if k==5 else '.')+f' On the test set, 1 and 5 passes yielded NMAEs of 0.0347 and 0.0332, while A6000 synchronized inference and covariate-construction time increased from {timing["1"]:.2f} to {timing["5"]:.2f}~s per mask job ({ratio:.2f} times). This describes an accuracy--cost trade-off, not a demonstrated globally optimal depth. Synchronous updating was held fixed; sequential updates remain a separate comparison.')
 su=para(su,'Refinement diagnostics use',f'Refinement depth selection uses 1,898 raw-observed validation gaps from the final chronological 20\\% of 21 training greenhouses. Up to 3 nonoverlapping gaps per greenhouse, scenario, masked-variable set and duration (6, 12, 24, 72 and 168~h) are sampled with seed~42 and deterministic offsets. Each starts after both the 80\\% split and the first 1,900 hourly positions. Candidates 1, 2, 3 and 5 share masks, contexts and frozen weights; zero passes is an initialization control. The criterion, fixed before validation inference, minimizes the equally weighted greenhouse mean of evaluated-hour-weighted NMAE. Exact ties favor fewer passes. Scoring ranges use only target-greenhouse training prefixes. The existing global training-prefix scalers are fixed. Reference candidates are other training greenhouses, excluding the target greenhouse entirely; available reference observations follow the retrospective main protocol. Hidden-target perturbation checks cover all 6 computed stages in two independent batches. The selected depth is {k}, shared by both backbone configurations and the forward-only control without separate optimization of those controls. This validation does not remove the development-informed nature of the test cohort.\n\n'+r'Test depth sensitivity uses the same 3,357 masks. Every pass reads a fixed preceding-pass snapshot and updates all masked targets simultaneously; reference selection remains fixed within a case, and the target gap estimate is excluded from its covariates. All 6 stages passed hidden-target perturbation checks on 15 scenario--duration cases. One-pass outputs reproduce the single-pass implementation. Four paired test contrasts compare the validation-selected depth with the remaining depths using Holm correction.')
 rows=[]
 for i in [0,1,2,3,5]:
  rr=stepstats.loc[f'BiTFI-refine{i}'];pv='--' if i==k else f"{contrasts.set_index('reference').loc[f'BiTFI-refine{i}','holm_p']:.4f}";label='Step 1 only' if i==0 else f'{i} '+('pass' if i==1 else 'passes')
  if i==k:label+=' (BiTFI)'
  rows.append([label,f'{va.loc[i,"mean"]:.4f}',f'{rr["mean"]:.4f}',f'{rr.sd:.4f}',f'[{rr.low:.4f}, {rr.high:.4f}]',pv])
 su=replace_table(su,'tab:refinement',table(r'Refinement-depth selection and test sensitivity. Validation and test use different sites and scoring ranges. CI is the test 95\% greenhouse bootstrap interval; Holm $p$ compares each alternative with the selected BiTFI depth.','tab:refinement',['Setting','Validation','Test NMAE','Test SD',r'95\% CI','Holm $p$'],rows))
 rows=[[{'BiTFI':'BiTFI','TimesFM3-univariate':'TimesFM3 (univariate)','Spatial-Ridge':'Spatial ridge','LI':'Linear interpolation'}[m],f'{r["mean"]:.4f}',f'{r.sd:.4f}',f'[{r.low:.4f}, {r.high:.4f}]'] for m,r in add.sort_values('mean').iterrows()]
 su=replace_table(su,'tab:additional',table(r'Reconstruction at 9 additional greenhouses for the 3 indoor variables. CI is the 95\% greenhouse bootstrap confidence interval.','tab:additional',['Configuration','NMAE','SD',r'95\% CI'],rows))
 su=su.replace('Contribution of refinement. (A) Mean greenhouse NMAE by refinement depth; bars show 95\\% bootstrap intervals. (B) Variable-specific error for Step~1 alone and BiTFI.',r'Refinement selection and contribution. (A) Training-site validation error. (B) Test error by depth. (C) Test error by variable for initialization and BiTFI. (D) RTX A6000 batched inference and covariate-construction time. Diamonds identify the validation-selected depth; error bars are 95\% greenhouse bootstrap intervals.')
 runtime=f'The primary GPU platform was NVIDIA RTX A6000 (48~GB). Across two diagnostic shards containing 2,238 test masks, synchronized initialization plus {k} refinement '+('pass' if k==1 else 'passes')+f' averaged {selected_s:.2f}~s per mask job. Initialization plus one pass averaged {timing["1"]:.2f}~s, versus {timing["5"]:.2f}~s through five passes. These timers include directional inference, fusion and refinement covariate construction, including reference selection; they exclude model loading, initial mask preparation and scoring. The complete six-stage diagnostic shards took 1307.7 and 1312.8~s on two A6000 GPUs. SAITS local and local + cross training took 148.9 and 165.5~s on an A6000; evaluation of both checkpoints took 54.8~s. Supplementary runs also used an RTX PRO 6000 Blackwell GPU: a single-pass, 3,357-mask inference-and-scoring run took 667.7~s (0.20~s per mask). The different timing scopes and hardware do not support a standardized inter-model latency comparison.'
 su=para(su,'The 3,357-case main BiTFI inference and scoring run',runtime)
 if k==5:
  pc=contrasts.set_index('reference')
  s=s.replace('This describes an accuracy--cost trade-off, not a demonstrated globally optimal depth.',f'The test contrasts of 5 passes with 2 and 3 passes were not statistically significant after Holm correction ($p={pc.loc["BiTFI-refine2","holm_p"]:.4f}$ and ${pc.loc["BiTFI-refine3","holm_p"]:.4f}$, respectively). This describes an accuracy--cost trade-off, not a demonstrated globally optimal depth.')
 # Match the B--C interpretation to the selected configuration, not the one-pass diagnostic.
 s=s.replace('The reversal of the aggregate ordering indicates that target composition and site coverage contribute to the apparent B--C difference.', 'The matched comparison retains a small B--C difference. Target composition and site coverage therefore do not fully explain the ordering.')
 s=s.replace('9 common sites reversed the ordering, giving NMAEs', '9 common sites gave NMAEs')
 # Qualify rankings against the completed, depth-matched control results.
 if allr['mean'].idxmin()!='BiTFI-TimesFM3':
  s=s.replace('achieved the lowest mean NMAE among the 21 evaluated settings:', 'achieved mean NMAE')
  s=s.replace('BiTFI achieved lower mean reconstruction error than the tested conventional, trained and frozen-model configurations', 'The primary TimesFM3-based BiTFI configuration achieved lower mean reconstruction error than the representative conventional, trained and frozen-model references')
 if bb.TFM3_reduction_percent<0:
  s=s.replace(r'a \BackboneGain{}\% reduction (paired Wilcoxon',r'a higher mean error (paired Wilcoxon')
  s=s.replace('Chronos~2 had the lowest univariate error, whereas TimesFM3 performed better within the full BiTFI framework.', 'Chronos~2 had the lowest univariate error and also performed better within the depth-matched BiTFI framework.')
  s=para(s,'Chronos~2 had lower error than TimesFM3 under matched',r'Chronos~2 had lower error than TimesFM3 under matched past-only univariate inference and within the depth-matched BiTFI control. The primary TimesFM3 configuration was retained as specified, while the backbone comparison reports the alternative performance directly. The shared refinement count was selected using TimesFM3 validation and was not independently optimized for Chronos~2. Backbone-specific responses to reversed contexts and covariate handling remain possible mechanisms, but were not isolated by this experiment.')
 (T/'TFM.tex').write_text(s);(T/'supplementary.tex').write_text(su)
 (V/'publication_numbers.json').write_text(json.dumps(dict(selected_refinements=k,macros=nums,initialization_contrast=init.to_dict(),forward_reduction=fwd,additional_contrast=addp.to_dict(),physical_MAE=phy.to_dict()),indent=2));print('Updated selected-depth manuscript',k)
if __name__=='__main__':main()
